### ISSUE TITLE
No `full.tsv` file for DUD-E

### ISSUE THREAD

**Issue by luoyunan** [samsledje/ConPLex_dev#2]
Hi Team,
This line in `src/data.py` requires a `full.tsv` file for DUD-E
https://github.com/samsledje/ConPLex_dev/blob/6d54414178cb926d20be3e7b508958b2e6e0c49c/src/data.py#L726
But there is no such file under the `dataset/DUDe` folder. Can we combine individual files inside that folder to create `full.tsv`? Alternatively, can we use the `full.tsv` available in the zenodo package of the MLSB version of this paper? Thanks!

**Comment by samsledje** [comment]
Hi luoyunan, `full.tsv` is quite large and we didn't want to include it in the repository. Thanks for pointing out this was missing! You can use the `full.tsv` in the zenodo package from MLSB, but I'm also adding a bash script in the `dataset/DUDe` folder to download the large file from our machines.

**Comment by luoyunan** [comment]
Thanks Samuel!
